services:
  footballleague.api:
    image: ${DOCKER_REGISTRY-}footballleagueapi
    container_name: FootballLeague.Api
    ports:
      - 8080:8080
      - 8081:8081
    build:
      context: .
      dockerfile: src/FootballLeague.API/Dockerfile
    depends_on:
       - footballLeagueDB

  footballLeagueDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: FootballLeague.DB
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=!Password123
    volumes:
        - "./sqldata:/var/opt/mssql/data/"

volumes:
  sqldata:
